# Flujo de trabajo para desplegar contenido estático en GitHub Pages
name: Deploy static content to Pages

on:
  # Ejecutar el flujo cuando se haga un push a la rama principal
  push:
    branches: ["main"]

  # Permitir ejecutar el flujo manualmente desde la pestaña Actions
  workflow_dispatch:

# Configuración de permisos para GitHub Pages
permissions:
  contents: read # Permisos de lectura para los contenidos
  pages: write   # Permisos para escribir en GitHub Pages
  id-token: write # Permisos necesarios para autenticación en GitHub Pages

# Configurar concurrencia para evitar conflictos en despliegues múltiples
concurrency:
  group: "pages" # Identificar un grupo de concurrencia para despliegues
  cancel-in-progress: false # Permitir que los despliegues actuales terminen

jobs:
  # Definir un trabajo llamado "deploy" para manejar el despliegue
  deploy:
    environment:
      name: github-pages # Configurar el entorno como GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }} # URL generada por Pages
    runs-on: ubuntu-latest # Especificar el sistema operativo para ejecutar el flujo
    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4 # Acción que descarga el repositorio en el entorno de ejecución

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Versión de Node.js requerida para el proyecto

      # Paso 3: Instalar las dependencias del proyecto
      - name: Install dependencies
        run: yarn install # Usa Yarn para instalar las dependencias definidas en package.json

      # Paso 4: Construir el proyecto
      - name: Build project
        run: yarn build # Ejecuta el script de construcción definido en package.json (genera el contenido en `dist`)

      # Paso 5: Subir el contenido generado en `dist` como un artefacto para despliegue
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist' # Solo sube el contenido de la carpeta `dist`

      # Paso 6: Desplegar el contenido a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Acción que publica el contenido en GitHub Pages
